Fixed that `pulp_file` presented its `python_package` as `pulp_file` instead of `pulp-file`.
