Fixed an issue with importing `async-timeout` in Python 3.11.
